### ISSUE TITLE
Subparser Demo with common arguments

### ISSUE THREAD

**Issue by jslirola** [chriskiehl/Gooey#133]
Hello, i'm trying to do an simple interface with a feature but i don't know if it's possible. I have three actions in the left column with common arguments, how can i design it?

I can write the arguments with every action but the code is redundant. I'd like to have a fixed block with the common args and below, the specific args for every action.

I see the action names are lowercase, is there some way to set it to uppercase? Thank you.

**Comment by chriskiehl** [comment]
I think you've already figured out the first part. A 'fixed block of code' sounds like a function to me. 

Something like this perhaps? 

```python
def main():
  parser = GooeyParser(description='example')
  subs = parser.add_subparsers(help='commands', dest='command')

  subparser_1 = subs.add_parser('option1')
  apply_my_common_args(subparser1)

  subparser_2 = subs.add_parser('option2')
  apply_my_common_args(subparser2)
 
  subparser_3 = subs.add_parser('option3')
  apply_my_common_args(subparser3)


def apply_my_common_args(subparser):
    subparser.add_argument('--foo', help='something1')
    subparser.add_argument('--bar', help='something2')
    subparser.add_argument('--baz', help='something3')
```


You can control how the fields are displayed by supplying a `metavar` argument when adding arguments to the parser. However! You'll need to use the GooeyParser in order for it to work. 

```python

from gooey import GooeyParser

def main():
    my_cool_parser = GooeyParser(description='Example')
    my_cool_parser.add_argument("FileChooser", help=file_help_msg, metavar="My Custom Display Name") 
```

I'm going to go ahead and close this since it's not really an issue with Gooey itself. But feel free to still comment here if you've got more questions.

**Comment by jslirola** [comment]
It works! Thanks. Is there some way to show an equivalent "metavar" for add_parser?

`another_parser = subs.add_parser('My_option', help='My Option')`

![issue_uppercase](https://cloud.githubusercontent.com/assets/6697559/11767759/ee66662c-a1b7-11e5-8762-85f6ded668c7.png)

Maybe showing the attribute help instead the name but i don't know how to do it. I read the documentation of argparse without luck.

**Comment by chriskiehl** [comment]
@jslirola, good catch! There currently is not a way to do that. 

I did some quick poking around and it looks like I can piggy back on `argparse`'s `prog` option as a means of customizing the display. 

![image](https://cloud.githubusercontent.com/assets/1408720/11768156/06b80ab2-a192-11e5-8934-ec9e6d860d49.png)

However, while displaying it in the GUI is simple, getting it to actually _work_ will require changing some of the Gooey internals so it keeps track of both the subparser and custom display name. 

Do you want to raise this as a new issue? 

I'll roll the functionality into the next commit (which may take a bit due to work schedules and holidays..).

**Comment by jslirola** [comment]
Done. I don't want bother you. If you think is not very difficult to customize i'll wait your commit.

Happy holidays.
