### ISSUE TITLE
checkboxes do not react to user input

### ISSUE THREAD

**Issue by drandreaskrueger** [chriskiehl/Gooey#148]
## Some checkboxes do not react to user input at all.

These

    parser.add_argument("--tt",   default=True, action="store_true",    help="tt")
    parser.add_argument("--ff",  default=False, action="store_false",   help="ff")

are broken.

Run this gist:  https://gist.github.com/drandreaskrueger/b66a7c4dde5bcd58e919

and you'll see.

There is no difference between [run 1 and run 2](https://gist.github.com/drandreaskrueger/b66a7c4dde5bcd58e919#file-gooeycheckboxesproblem-py-L11-L22) for those checkboxes.

Or is it me, and I haven't understood it yet? Then please explain, thanks a lot!

**Comment by chriskiehl** [comment]
+:100: for providing a gist of your issue! 

Gooey is behaving correctly (for once!). 

Firstly, I modified your gist to remove Gooey and use plain old `argparse`. You can check it out here: https://gist.github.com/chriskiehl/dd64741019aa270a4b39. That takes Gooey out the equation so we can just mess around with the raw CLI args. 

So, Let's step through this. 

You set up an argument where the default is `True`. That means that if no command line argument is supplied, then `tt` will receive a value of `True`. 

```python
parser.add_argument("--tt",   default=True, action="store_true",    help="tt")
```

And if we run your program with _no arguments_, we'll see that it indeed defaults to True 

```
$ python drandreaskrueger_example.py
--truefalse True
--falsetrue False
--truetrue True
--falsefalse False
```

Now, the look at the second part of the argument, the `action` param:

```python
parser.add_argument("--tt",   default=True, action="store_true",    help="tt")
```

That is set to `store_true`, which, means, if it _receives_ a command line argument, that it will set the value of `tt` to True. 

Now we run your program and give it the `-tt` flag 

```
$ python drandreaskrueger_example.py -tt
--truefalse True
--falsetrue False
--truetrue True
--falsefalse False
```

And.. we get the exact same output. The same thing would happen with your `-ff` example as well. You've structured them such that the _absence_ of a CLI argument produces the same thing as the `presence` of a CLI argument. 

So that's why it looks like the check boxes aren't working. They _are_ working (behind the scenes Gooey just feeds the `--tt` and `--ff` arguments to your program), it just _looks_ like they're not, because regardless of the program input, they ultimately end up in the same state.

**Comment by drandreaskrueger** [comment]
Chris, wow. Thanks a million for this examination, and perfect presentation.   Great!

> it just looks like they're not, because regardless of the program input, they ultimately end up in the same state.

Hmmm ...


Then perhaps it might make sense to issue some warning to never combine 

    default=True,  action="store_true"

or

    default=False, action="store_false"

because in those cases the checkbox user input (nor the argparse.ArgumentParser CLI input if I understand you correctly) is not getting passed on to the program?

Admittedly, it was my first day with Gooey, and I had never used argparse.ArgumentParser before, so I faced a bit of a learning curve there. But that checkboxes input does not result in any variable change did confuse me a bit. Very happy that you clarified this for me. Very.  
I suggest you include that topic into your manual.

### Taking breaks from coding I should :-)

After I had typed the whole thing, and had come up with that foobar way of presenting it, and tested and debugged the script, and created the example gist, and had it all uploaded, and the computer switched off ... I realized that I only need 2, not 4 options anyways. 

## solutions: 
### default=True
If I need a ``default=True checkbox``, I will use the 

    default=True,  action="store_false"
checkbox, and *negate the args parser answer*.

### default=False
If I need a ``default=False checkbox``, I will use the 

    default=False,  action="store_true"
checkbox, and *take the args parser answer as the answer*.


*Correct?*

**Comment by drandreaskrueger** [comment]
Now I am almost there. 

I have just had the idea how to **automate that negation** in case of ``default=True``. 

My (real app's) code looks like this now:

    parser = ArgumentParser(description="Still learning argparse and gooey.")

    parser.add_argument("--errors", default=False, action="store_true" , help="Show each file access error.")
    parser.add_argument("--omit",   default=True,  action="store_false", help="Omit empty days in printout.")
  
    args = parser.parse_args()

    print "These are the arg parser results:"
    for p in ("errors", "omit"): print "%s : %s" % (p, args.__getattribute__(p))

    print "Now solve the correct conversion True <-> False:"
    for p, negate in (("errors", False), 
	                  ("omit",   True)): 
        value = args.__getattribute__(p)
        value = not value if negate else value 
        print "%s : %s" % (p, value)

Please help: What is the way to read out the settings from ``parser``?

The idea is that instead of repeating the default-choice via ``(("errors", False), ("omit",   True))``, I could read out the ``parser.argument["errors"].default``, and ``parser.argument["omit"].default`` - and depending on those choices I could negate, or not.

But I don't understand how ArgumentParser is internally storing the ``.add_argument`` attributes. You do - that's how you built Gooey, right?

Thanks!
