### ISSUE TITLE
How to create a multi-line text field (text area)?

### ISSUE THREAD

**Issue by gregpinero** [chriskiehl/Gooey#165]
I'm looking through the code but I haven't seen it.  Thanks!

**Comment by chriskiehl** [comment]
Hm.. Y'know that may have been one that I missed. I'll check this later tonight.

**Comment by chriskiehl** [comment]
Added! 

Gooey now has a `Textarea` component. 

![image](https://cloud.githubusercontent.com/assets/1408720/16824191/c754cf6a-4937-11e6-8d4c-64d51ea830b8.png)

You can use it by specifying `widget='Textarea'`

e.g. 

    parser.add_argument('-t', '--textarea', default="I'm on \na new line", type=str, help='A multiline textarea', widget='Textarea')

You'll need to pull from master in order to get the latest changes. For whatever reason, I'm unable to push any changes to PyPi : (

**Comment by gregpinero** [comment]
This is great! Thanks!

**Comment by chriskiehl** [comment]
No problemo. Thanks for the report!
