### ISSUE TITLE
Issue parsing lists with Gooey

### ISSUE THREAD

**Issue by aforsythe** [chriskiehl/Gooey#183]
I have the following code

	import argparse
	from gooey import Gooey, GooeyParser

	def get_args():
		"""Get CLI arguments and options"""
		parser = GooeyParser(description='error test', 
                                 formatter_class=argparse.ArgumentDefaultsHelpFormatter)

		parser.add_argument('--input', help='List of values', default=['a', 'b', 'c'])

		args = parser.parse_args()

		return args

	@Gooey()
	def main():

		args = get_args()

		l = args.input

		for count, each in enumerate(l):
			print each

	if __name__ == "__main__":
		main()

Unfortunately it returns:

	[
	'
	a
	'
	,

	'
	b
	'
	,

	'
	c
	'
	]

If I use the same code but comment out the `@Gooey` decorator, I get :

	a
	b
	c

If I do the following :

	import argparse
	import ast
	from gooey import Gooey, GooeyParser

	def get_args():
		"""Get CLI arguments and options"""
		parser = GooeyParser(description='error test', 
                                 formatter_class=argparse.ArgumentDefaultsHelpFormatter)

		parser.add_argument('--input', help='List of values', default=['a', 'b', 'c'])

		args = parser.parse_args()

		return args

	@Gooey()
	def main():

		args = get_args()

		l = ast.literal_eval(args.input)

		for count, each in enumerate(l):
			print each

	if __name__ == "__main__":
		main()

It returns:

	a
	b
	c

but using that same code and commenting out the `@Gooey` decorator produces:

	Traceback (most recent call last):
	File "/Users/alex/Source/AT_analyzer/test.py", line 30, in <module>
	main()
	File "/Users/alex/Source/AT_analyzer/test.py", line 24, in main
	l = ast.literal_eval(args.input)
	File "/Users/alex/anaconda3/envs/at_analyzer_env/lib/python2.7/ast.py", line 80, in literal_eval
	return _convert(node_or_string)
	File "/Users/alex/anaconda3/envs/at_analyzer_env/lib/python2.7/ast.py", line 79, in _convert
	raise ValueError('malformed string')
	ValueError: malformed string

I'd like to be able to use the same code with and without Gooey especially since you [can not debug](https://github.com/chriskiehl/Gooey/issues/144) while using Gooey. Any help would be greatly appreciated.

**Comment by chriskiehl** [comment]
This is actually not a Gooey quirk, but a misunderstanding of how Argparse reads stuff off the commandline. 

Your default is a different type (lists) than what Argparse knows about (strings). You can see this by actually passing data into your script from the command line. `youscript.py --input blah`. The first thing you should note is that you cannot pass lists of things as an argument: `youscript.py --input ['a', 'b', 'c']` fails because argparse doesn't know what to do with it. You'd have to first wrap it in quotes. `youscript.py --input "['a', 'b', 'c']"`. Now Argparse can understand it, but it still treats it as a string, which'll cause you to iterate over its characters (the behavior you see with Gooey)

```
[
'
a
'
,

'
b
'
,

'
c
'
]
```

So the summary here is, if you want to work with lists of things on the command line, you need to use [nargs](https://docs.python.org/3/library/argparse.html#nargs) and pass in your data without any kind of python syntax around it. e.g. 

```
    parser.add_argument(
        '--input',
        nargs='+',
        help='List of values',
        default=['a','b','c'])
```
and 

`yourscript.py --input a b c` 

That gives you the behavior you want.

**Comment by tboyce021** [comment]
This doesn't work if you just leave the defaults Gooey populates:

![image](https://user-images.githubusercontent.com/1326315/57469686-d2217600-724c-11e9-8009-e70010ddb239.png)

then `print(parsed_args.input)` gives

```
["['a',", "'b',", "'c']"]
```

You have to modify what Gooey populates as the default in order for it to work:

![image](https://user-images.githubusercontent.com/1326315/57469783-101e9a00-724d-11e9-91fb-2983b21a3dd2.png)

yields

```
['a', 'b', 'c']
```

However, `yourscript.py --ignore-gooey` works fine with those defaults, as does argparse.

If you change it to `defaults='a b c' then Gooey will make the correct list but regular argparse and `--ignore-gooey` will just treat it as a single string.
