### ISSUE TITLE
Can we make this more generic?

### ISSUE THREAD

**Issue by supercheetah** [chriskiehl/Gooey#191]
I think it would be nice to be able to extend this to other command line tools.  I know that PowerShell scripts/commandlets have a pretty specific way of accepting command line parameters that we could probably take advantage of.  A lot of /bin/sh scripts (well, GNU anyway) use a fairly standard --help format.

How feasible would this be?

**Comment by chriskiehl** [comment]
Gooey being extended to other tool chains is limited only by the desire of other communities to build bindings for their specific tooling. 

These days, Python is an implementation detail for Gooey. As is, Gooey just runs whatever `target` its given. As long as that target talks over `stdout` and `stderr`, language doesn't matter at all. Thus, the project is firmly divided into two pieces: 

1. Bindings - these are responsible for parsing a given CLI library and converting it to a Gooey buildspec. For historical reasons, the available bindings are, of course, Python based and target argparse due to its ubiquitous and builtin status. However, additional bindings can be easily made of [insert your fav technology here]. 
2. Gooey Proper - everything is powered by the JSON file generated by the bindings. This side can be bundled as an executable thus hiding the "python" implementation entirely. 

Personally, I've packaged a few Clojure tools with Gooey with minimal(ish) finagling. 

However, to really make Gooey a widely available tool a few things would need to happen: 

1. formally splitting the project into `GooeyBindings` and `GooeyCore` thus completely decoupling it from Python
2. Shipping an opaque binary for environment [X]
3. Maybe (probably) custom packaging tooling?

For instance, getting Gooey to work with Clojure basically boils down to generating an Uberjar and then using Pyinstaller to package Gooey along with the jar. in the current state, this unfortunately requires intimate knowledge of how PyInstaller bundles and unpacks dependencies in order to work. Since bundles are a big "sell" of Gooey, figuring out packaging would take some thought, but if done well, could truly be general and pretty fudging cool.
