### ISSUE TITLE
Two Listboxes - corruption when chosing multiple options

### ISSUE THREAD

**Issue by Krasiu** [chriskiehl/Gooey#228]
My program allows users to chose from two listboxes, and works fine when user selects multiple values from first listbox (County) and only one value from Estate type:

![image](https://user-images.githubusercontent.com/12200435/32407488-2716bbfe-c18a-11e7-94b5-d9c5db990650.png)

For debugging purpouses I am printing parsed arguents, so I get:

> Namespace(counties=['Baltimore', 'Baltimore City', 'Calvert'], date_from='2017-11-04', date_to='2017-11-04', estates=['FP'])

Looks good. However when I select second value from Estate type listbox:

![image](https://user-images.githubusercontent.com/12200435/32407514-9c5dc010-c18a-11e7-979e-a9148a8d9e70.png)

I am getting an error:

> maryland_gov.py: error: argument County: invalid choice: 'FP' (choose from 'Allegany', 'Anne Arundel', 'Baltimore', 'Baltimore City', 'Calvert', 'Caroline', 'Carroll', 'Cecil', 'Charles', 'Dorchester', 'Frederick', 'Garrett', 'Harford', 'Howard', 'Kent', 'Montgomery', "Prince George's", "Queen Anne's", 'Somerset', "St. Mary's", 'Talbot', 'Washington', 'Wicomico', 'Worcester')

So it somehow mixes up those two listboxes:

```
@Gooey(advanced=True)
def main():
    parser = GooeyParser(description="Maryland Registres Scraper")
    parser.add_argument('counties', metavar='County', help="Pick counties", widget="Listbox", nargs='+', choices=list(counties.keys()))
    parser.add_argument('estates', metavar='Estate type', help="Pick estate types", widget="Listbox", nargs='+', choices=estate_types)
    parser.add_argument('date_from', metavar='Date from', help="Pick start date", widget="DateChooser")
    parser.add_argument('date_to', metavar='Date to', help="Pick end date", widget="DateChooser")

    args = parser.parse_args()
    print(args)
```

**Comment by chriskiehl** [comment]
Here's what's up: arparse doesn't know how to get differentiate the two sets of `nargs` arguments. Although, why it works in your first case is a total mystery to me. 

From the command line perspective, what gets generated is 

```
yourscript.py "Baltimore" "Baltomore City" "calvert" "FP" "LO"
```

`nargs=+` is a 1 or more type of consumer, so it greedily chews through through those tokens until it hits "FP" and then explodes because it is an unexpected parameter to your `countries` arg. There's a bit in the docs about it 

>Note that it generally doesn't make much sense to have more than one positional argument with nargs='*'



A work around, if you're OK with changing your CLI API just a bit, is to make those items optional types, but with the `required=true` flag set. e.g. 

```
from gooey import Gooey, GooeyParser


@Gooey(advanced=True)
def main():
    parser = GooeyParser(description="Maryland Registres Scraper")
    parser.add_argument('--counties', required=True, metavar='County', help="Pick counties", widget="Listbox", nargs='+', choices=['az', 'qw', 'er, df'])
    parser.add_argument('--estates', required=True, metavar='Estate type', help="Pick estate types", widget="Listbox", nargs='+', choices=['asdf', 'qwer', 'erty'])
    parser.add_argument('--date_from', required=True, metavar='Date from', help="Pick start date", widget="DateChooser")
    parser.add_argument('--date_to', required=True, metavar='Date to', help="Pick end date", widget="DateChooser")

    args = parser.parse_args()
    print(args)

main()
```

This will still draw the UI the same. 

![image](https://user-images.githubusercontent.com/1408720/32407909-ef7a9572-c14c-11e7-8cdd-d0e277c0613b.png)

However, behind the scenes, it'll generate a command like this: 

```
yourscript.py --countries "Baltimore" "Baltomore City" "calvert" --estates "FP" "LO"
```

Which allows argparse to know when to stop consuming tokens for a given group, and correctly assign all of your selections to the correct bucket

```
Namespace(counties=['az', 'qw'], date_from='2017-11-04', date_to='2017-11-04', estates=['asdf', 'qwer', 'erty'])
```

BTW, thanks for all the details provided in your issue. Code, screen shots, debug output are absolutely **awesome** to find when I look at an issue!

**Comment by Krasiu** [comment]
Thank you so much, everything works with your fix. It's saturday and you responded within an hour, I am absolutely amazed!
