### ISSUE TITLE
[Feature Request] Adding Windows Version Data to executable created with pyinstaller

### ISSUE THREAD

**Issue by dragancla** [chriskiehl/Gooey#231]
When using pyinstaller to create the executable using the .spec file I find it impossible to also add Windows Version Data to the executable. Scenarios:
pyinstaller build.spec -> creates the app without Windows Version Data
pyinstaller --version-file=version.txt build.spec -> creates the app without Windows Version Data
pyinstaller build.spec + pyi-set_version version.txt executable.exe (as per their manual) -> makes the executable 234 KB in size but adds Windows Version Data

Since using  pyinstaller with the .spec file is the only way to create an executable when using Gooey I'm wondering if it's possible to somehow incorporate Windows Version Data during the build process

**Comment by chriskiehl** [comment]
Unfortunately, anything beyond the most basic Pyinstaller stuff is pretty much over my head. I also don't know what Windows Version Data is. 

Since this seems orthogonal to Gooey itself and only related to adding additionally information via PyInstaller, I'd suggest hitting up the PyInstaller folks directly. 

Good luck!
