### ISSUE TITLE
Unwanted CMD.EXE UNC message in Status window

### ISSUE THREAD

**Issue by TravStu22** [chriskiehl/Gooey#239]
Hi, when I run a Gooey script located on a server the following message is printed in the Status window:

'\\dm003\test\dev'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.

What is the best way to suppress this message? The script runs as expected otherwise.
Hitting Restart will reprint the message. What part of Gooey is using CMD.EXE?

**Comment by chriskiehl** [comment]
Could you provide a minimal, runnable code example demonstrating your problem?

**Comment by TravStu22** [comment]
When this script is executed from a UNC directory:
```
from gooey import Gooey, GooeyParser

@Gooey()
def main():
    parser = GooeyParser()
    arguments = parser.parse_args()

    print('Hello.')

if __name__ == '__main__':
    main()
```

The Status window writes:

> '\\dm003\test\dev'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
Hello.
 
I'm running 32bit Python 3.6.3 on Windows 10 with Gooey 0.9.5.2

**Comment by chriskiehl** [comment]
Just as a shot in the dark, could you try modifying Gooey's code and seeing if that resolves your issue? I don't actually know what a UNC directory is, nor how to set one up, so I'm unable to test this on my end (also: lazy). 

In your virtualenv's site-packages for Gooey, edit processor.py lines [49](https://github.com/chriskiehl/Gooey/blob/master/gooey/gui/processor.py#L49) and [54](https://github.com/chriskiehl/Gooey/blob/master/gooey/gui/processor.py#L54) so that `shell=False`. Then try again. It may be CMD.exe is your default shell, and Gooey is spawning it behind the scenes in order to launch your code. 

This is 100% just a guess though.

**Comment by TravStu22** [comment]
Good guess, this fixed it. Thanks!

**Comment by chriskiehl** [comment]
Huzzah! ^_^

I'll push an update soon (within a year, surely) that makes the shell behavior configurable so you don't need to modify any internals.

**Comment by mhoffman1193** [comment]
Just used this `shell=False` method to solve the problem myself.  Thanks for the help.

**Comment by ed2050** [comment]
I know it's old but here's more info for the record -
I had same issue.  Since adopted code fix is not described above, it's this: pass requires_shell = false as arg to Gooey decorator.

@chriskiehl [UNC](https://en.wikipedia.org/wiki/Path_(computing)#UNC) is just a Microsoftie name for a network path, e.g. \\ServerName\path\to\resource.  Because drive letters suck and aren't universal, it's better practice to access network paths by [UNC name](https://stackoverflow.com/questions/21482825/find-unc-path-of-a-network-drive) instead of [mapped drive letter](https://support.microsoft.com/en-gb/windows/map-a-network-drive-in-windows-29ce55d1-34e3-a7e2-4801-131475f9557d).

If you never have to deal with Windows craziness then consider yourself very lucky.
