### ISSUE TITLE
Return back to Settings automatically after run without manually clicking Edit

### ISSUE THREAD

**Issue by dagrha** [chriskiehl/Gooey#249]
Gooey is a great program-- thank you for open-sourcing it and for your work on it.

Is there a way to have the program return back to the "Settings" view after a successful run? In other words, after options are set in the Settings window and Start is clicked, the program runs and ends up at a "Finished" screen with an "Edit" button. If I click the Edit button it takes me back to the Settings view. Is there a way to automatically return to the Settings window without having to manually click Edit?

**Comment by chriskiehl** [comment]
I can add one : )

**Comment by dagrha** [comment]
Fantastic, thank for being willing to do that, Chris!

Is the solution a matter of "simulating" a click event? In other words, use wx.PostEvent() to "click" the Edit button programatically? Or something else?

**Comment by chriskiehl** [comment]
If you're interested in doing it yourself (and making a pull request! 😄 ), the basic flow of adding a new option to Gooey is: 

1. Add it as an option in [config_generator.py](https://github.com/chriskiehl/Gooey/blob/master/gooey/python_bindings/config_generator.py).  
2. In [application.py](https://github.com/chriskiehl/Gooey/blob/master/gooey/gui/containers/application.py#L117) all that config data from config_generator is present on the instance as `self.buildSpec`. In this class there is a handler called `onComplete`. You'd just add a call to `showConfiguration()` within the `onSuccess` path if your flag is present (e.g. `if self.buildSpec.get('YOUR_OPTION', False): ...`).  Note: I'd keep the error path the same so that it doesn't silently fail in the case of an error 
3. Update the Configuration section of the README outlining your new option 
4. Profit  

Let me know if you want to take a stab at it.

**Comment by dagrha** [comment]
I will take a stab at it. Thanks for the rundown on how to accomplish it. 👍

**Comment by chriskiehl** [comment]
Closing. Fixed by your pull here: d01afc9b7be5637e7d4eb80ba49f11dbe0ebd8c7 

Nice work!
