### ISSUE TITLE
How to make a group visible (title, description) even if no .add_argument on it ? 

### ISSUE THREAD

**Issue by FrancoisSchnell** [chriskiehl/Gooey#267]
Thanks so much for gooey, so useful.

I wish i could have a tab with just some infos and contact.

For that I'm using tabbed_groups=True  and created 2 groups (one for the inputs and one for general infos and contact).
The 2nd group have no inputs and therefore is not displayed but I'd like to use its title and description as an info tab. 

Any idea, or another way to add this ?
Thanks!

**Comment by chriskiehl** [comment]
Hmm.. 

There's not currently a good way to get you what your after. We could _probably_ hack it in there by adding a `ignore_empty_groups=(True|False)` kind of flag. However, I think what you ultimately want, a place to show About info, may be better served by going the more native/familiar title bar + "About" option, rather than commingling the About section with the Arguments section. Something like:  

![image](https://user-images.githubusercontent.com/1408720/36710458-fcb517d6-1b32-11e8-8ee3-b4f90331c746.png)

...or something like that. 

I'm open to opinions.

**Comment by metadirective** [comment]
The way you describe it would be perfect for me 👍 
Maybe something which could be build from the Gooey options?

@Gooey(
...
menu_help_about="Your about string here"
menu_help_url="your url here"
...
)

Having an option for about/help would be very handy :)

**Comment by chriskiehl** [comment]
Alright! Menu Bars added. They look and feel way better than I expected! 

They'll be in the 1.0.2 release or you could check them out ahead of time on the branch here: https://github.com/chriskiehl/Gooey/commit/73b08c126a64164c6ddcfa7114024ed4336dc3f1 (just note, that's an active dev branch, so may be broken from time to time)

![image](https://user-images.githubusercontent.com/1408720/47250909-74782a00-d3df-11e8-88ac-182d06c4435a.png)
