### ISSUE TITLE
Mutually exclusive group with check box subitems

### ISSUE THREAD

**Issue by alexandra-m-reimers** [chriskiehl/Gooey#274]
Hi there,
I'm quite new to Gooey and I've been trying to make Gooey interface which has a checkbox as subitem for each mutually exclusive item. Something like:
* item 1
   - check box 1
* item 2
  - check box 2
The important thing is that item 1 and item 2 are mutually exclusive here.

I would expect this to work maybe using subparsers like:

```
subparsers = parser.add_subparsers(help='')

# create the parser for the item 1 command
parser_a = subparsers.add_parser('--item_1', help='item 1 help')
parser_a.add_argument('--check_box_1', action='store_true', help='check box 1 help')

# create the parser for the item 2 command
parser_b = subparsers.add_parser('--item_2', help='item 2 help')
parser_b.add_argument('--check_box_2', action='store_true', help='check box 2 help')
```

Unfortunately this crashes with "Gooey doesn't currently support top level required arguments when subparsers are present."

Now, I was thinking I can achieve the same with a mutually exclusive group. But I don't exactly see how.
So is there no way in Gooey to implement such an interface?

Thanks in advance for the help!

**Comment by chriskiehl** [comment]
Hard to know what's up without a full, runnable code example. However, if I'm understanding what you want correctly, a top-level mutually exclusive group, check out this example: https://github.com/chriskiehl/GooeyExamples/blob/master/examples/dynamic_updates.py . Give that a run. It has a single exclusive option. One is a checkbox, the other is a listbox.  

Note: checkboxes will _not_ show up when they're inside of a mutually exclusive grup, as selecting an option is implicitly selecting the checkbox.  

Top level required positional _will_ throw the error you're seeing because it's somewhat undefined at the moment how to present mixed options like that in the UI.

**Comment by chriskiehl** [comment]
Closed due to inactivity.
