### ISSUE TITLE
DirChooser errors with "The filename, directory name, or volume label syntax is incorrect."

### ISSUE THREAD

**Issue by beigela** [chriskiehl/Gooey#280]
`DirChooser` isn't working for me. The screen shows the error message:
`The filename, directory name, or volume label syntax is incorrect.`

I get this error whether I select the path like this:
`C:\Users\Username\Documents\test_dir`
or like this:
`.\test_dir`

I also briefly tested this code with `FileChooser`, and it seems to have the same errant behavior.

I recall I had similar code working on an older version of Gooey (on a different machine), and I didn't have this problem. Any insight would be much appreciated!

#### Setup:
Windows 10 x64 (and Windows 7 x64)
Python 2.7
Gooey 1.0.0

#### My code:
```python
import sys
from gooey import GooeyParser as ArgumentParser
from gooey import Gooey


@Gooey(terminal_font_family="Courier New")
def set_gooey():
    return


def main():
    # If no args were given, display the GUI by calling a decorated function
    if len(sys.argv) == 1:
        set_gooey()

    # Parse command line arguments
    parser = ArgumentParser(description='Testing Gooey DirChooser.')
    parser.add_argument("path", widget="DirChooser",
                        help="Directory.")
    args = parser.parse_args()

    print "Done"


if __name__ == '__main__':
    main()
```

#### The error in the GUI:
![screenshot_2018-03-27_13-47-44](https://user-images.githubusercontent.com/7630544/37985670-6bb1a546-31c7-11e8-8ac8-b903ed2fa03d.png)

#### The CLI output corresponding to the screenshot above:
```batch
C:\Users\Username\Documents> python gooey_test.py
"C:\Python27\python.exe" -u "gooey_test.py" --ignore-gooey "C:\Users\Username\Documents\test_dir"
```

#### Running the command from the above output:
This works as expected (without the GUI, of course).
```batch
C:\Users\Username\Documents> "C:\Python27\python.exe" -u "gooey_test.py" --ignore-gooey "C:\Users\Username\Documents\test_dir"
Done
```

**Comment by chriskiehl** [comment]
So, is the example you provided actually the example that produces the error? I've had no luck in reproducing, unfortunately.  

I'm a bit unsure what could be the cause, to be honest. The CLI string doesn't appear to be malformed. If your example is really the full thing, and the string is not malformed, then that'd point towards the Python location being invalid -- but Gooey gets that from `sys.argv`.. so that can't be it. It seems like the only spot for weirdness would be the hand off when Gooey spawns your code via `Popen`. 

* As a wild guess, if you run your code with `@Gooey(requires_shell=True)` does the issue persist? 
* Does it happen regardless of which directory you chose? For instance, do ALL directories fail? Can you select a root one right off of `C:\`? 
* if you run Gooey with _no arguments_ does the issue remain?

**Comment by chriskiehl** [comment]
Closed due to inactivity
