### ISSUE TITLE
Help text for subparsers not displayed

### ISSUE THREAD

**Issue by willwill2will54** [chriskiehl/Gooey#288]
Checklist:
 - [x] OS - Mac OS 10.13.4
 - [x] Python Version - 3.6.5
 - [x] Gooey Version - 1.0.0?, latest?, ran-pip-to-make-sure-was-latest-and-it-was?
 - [x] Thorough description of problem.- As part of argparse you can add help text to subparsers
     - [x] Expected Behavior - Help text is shown
     - [x] Actual Behavior - Help text is not shown
 - [x] A minimal code example -
```python
@Gooey(program_name='some program')
def main():
    someparser = GooeyParser(description='Some words')
    someparsers = someparser.add_subparsers(dest='someplace')
    somesubparser = someparsers.add_parser('someoption', help='AAAAAH! CROCODILES! Someone help me!')
    someothersubparser = someparsers.add_parser('someotheroption', help='foo')
    someoption = somesubparser.add_argument('-somecrocodile', action='store_true', help='Nothing to see here, move along.')
    someparser.parse_args()
# And yet no-one hears...
```
 - [x] Screenshot (if visual quirk):
![image](https://user-images.githubusercontent.com/38622599/39409087-ca05179c-4bd8-11e8-8853-365ade7af811.png)
 - [x] Anything else you may think will be helpful - Nope!

Your app is great, and should this niggle be resolved, it would suit my purposes perfectly.

**Comment by chriskiehl** [comment]
I went down the path of adding this, but I'm currently stuck on what the UX should actually look like for all of Gooey's various modes (for instance, there's no good place to show a top-level subparser group description in the tabbed layout). 

However, you can still totally get what you're after by using argument groups. Instead of using the default Optional Arguments group provided by Argprase, make a custom one to house your arguments. You can then add descriptions on a group-by-group basis. 

Note: there is a textwrap issue in the current [version. 1.0.2](https://github.com/chriskiehl/Gooey/commit/d71489cc24f30a19c0712c00891928a1942a91ec) has corrected wrapping behavior. 

I'm going to close this since there are alternative methods to accomplishing the goal. If anyone comes up with solid ux approaches, feel free to throw 'em into the ring. 

```
@Gooey(program_name='some program')
def main():
    someparser = argparse.ArgumentParser(description='Some words', formatter_class=CustomHelpFormatter)
    someparser = GooeyParser(description='Some words', formatter_class=CustomHelpFormatter)
    someparsers = someparser.add_subparsers(dest='someplace')
    somesubparser = someparsers.add_parser('someoption')
    croc_facts = somesubparser.add_argument_group(
        'Just Crocodile Things',
        description='There are 13 species of crocodiles, so there are many different ' +
                    'sizes of crocodile. The smallest crocodile is the dwarf crocodile. ' +
                    'It grows to about 5.6 feet (1.7 meters) in length and weighs 13 to 15 pounds '
    )
    someothersubparser = someparsers.add_parser('someotheroption', help='foo')
    someoption = croc_facts.add_argument('-somecrocodile', action='store_true', help='Nothing to see here, move along.')
    someparser.parse_args()
```


![image](https://user-images.githubusercontent.com/1408720/47271920-d09f9300-d532-11e8-9bd8-c755e51ca9a3.png)

Or with a nice group border: 


```
@Gooey(program_name='some program')
def main():
    someparser = argparse.ArgumentParser(description='Some words', formatter_class=CustomHelpFormatter)
    someparser = GooeyParser(description='Some words', formatter_class=CustomHelpFormatter)
    someparsers = someparser.add_subparsers(dest='someplace')
    somesubparser = someparsers.add_parser('someoption')
    croc_facts = somesubparser.add_argument_group(
        'Just Crocodile Things',
        description='There are 13 species of crocodiles, so there are many different ' +
                    'sizes of crocodile. The smallest crocodile is the dwarf crocodile. ' +
                    'It grows to about 5.6 feet (1.7 meters) in length and weighs 13 to 15 pounds ',
        gooey_options={
            'show_border': True,
        }
    )
    someothersubparser = someparsers.add_parser('someotheroption', help='foo')
    someoption = croc_facts.add_argument('-somecrocodile', action='store_true', help='Nothing to see here, move along.')
    someparser.parse_args()
```

![image](https://user-images.githubusercontent.com/1408720/47271929-03498b80-d533-11e8-82e2-67f537d71066.png)

**Comment by willwill2will54** [comment]
Thanks. This has me sorted. You really have something special in this.
