### ISSUE TITLE
 ValueError: can't have unbuffered text I/O in python 3.5

### ISSUE THREAD

**Issue by r92546024** [chriskiehl/Gooey#289]
Hello ,

When using python 3.5 in windows 7 , run the following two command for pyinstaller package purpose 

    nonbuffered_stdout = os.fdopen(sys.stdout.fileno(), 'w', 0) 
    sys.stdout = nonbuffered_stdout # for package gooey output

Will show the following error

  File "C:\Python35\lib\os.py", line 1074, in fdopen
    return io.open(fd, *args, **kwargs)
  ValueError: can't have unbuffered text I/O

if using python 2.7 , it won't have the error.  How to workaround it in python 3.5 ?

**Comment by Kronen** [comment]
unbuffered reading is only supported for binary mode

**Comment by Kronen** [comment]
With PEP3116, python 3 introduced a layered I/O library in the io module that separates buffering and text-handling features from the fundamental read and write operations.

So unbuffered io only works for binary mode:

`if buffering == 0:
        if binary:
            return raw
        raise ValueError("can't have unbuffered text I/O")`

Since Python 3.3 print() supports the keyword argument "flush"
`print('Hello World!', flush=True)`

**Comment by r92546024** [comment]
Thanks.  @Kronen 
After add **flush=True** in each print() , it's worked now at python 3.5.
