### ISSUE TITLE
How to debug gooey application?

### ISSUE THREAD

**Issue by chenerlich** [chriskiehl/Gooey#349]
Hi,

2 questions:
1. If i run Gooey on pycharm and i add breakpoints, the execution doesn't break. I can't currently debug this kind of programs. Am i missing something?
2. Is there a flag to run Gooey apps in CLI?

Btw,
Awesome project! Well done!

Thanks.

**Comment by chriskiehl** [comment]
Howdy! 

1. So those PyCharm break points don't work because Gooey runs your program in a totally separate process (via `Popen`). 
2. Yep! It's called `--ignore-gooey`. You can setup your IntelliJ to pass that as a run time argument, and then all those break points will work again (of course, assuming you've _also_ provided the relevant CLI args request to run your program). Alternatively, you could just comment out the decorator.
