### ISSUE TITLE
Hidden fields and dynamical default values

### ISSUE THREAD

**Issue by mariaeiou** [chriskiehl/Gooey#396]
Hi there!
I have some requests for features that I can't find so far:

- hidden input fields, that show up once you click on an 'advanced settings' button/check box/radio button or similar

- dynamical default values of input text fields (that change depending on a selected value above)

Is something like that implemented right now?

**Comment by chriskiehl** [comment]
Howdy howdy! 

On the first point, if you squint, you can _kind_ of do this with Mutually Exclusive Groups now. It won't be _hidden_, but the widget will be disabled ("greyed out") until the user specifically opts in to using it. 

Second point: Gooey currently has an experimental feature which can handle [some dynamic values](https://github.com/chriskiehl/Gooey#using-dynamic-values), but its discovery mechanism is pretty basic and only runs when the user hits the edit screen. So, not exactly what you're after. 

I've toyed around with a few ideas for enabling dynamic changes in response to user actions, but so far, they've all been shelved due to either complexity or user burden. I still vaguely feel like it _could_ be done, but a lot more thinking would be required around how the API / interactions would work. In the grand scheme of things though, in the 5(?) years Gooey's been available, this has only come up _maaaybe_ once before, so it's niche enough not to get any dev effort thrown at it.
