### ISSUE TITLE
monospaced_display should be True by default

### ISSUE THREAD

**Issue by bje-** [chriskiehl/Gooey#562]
The default value for the monospaced_display parameter is `False`. I think there is a good case for it to be `True` by default, given that many command line applications are designed to run in a terminal in a monospaced font.

**Comment by chriskiehl** [comment]
That's a decent argument for making it the default, but, alas, it is _not_ the default, and I'm pretty committed to not introducing breaking changes, even if it's something like a font change! 

So, if I had a time machine: this would be an accepted suggestion, but since I don't, it'll have to remain as is ^_^
