### ISSUE TITLE
Permission denied: '/Library/Python/2.7/site-packages/Gooey-0.1.0-py2.7.egg/gooey/_tmp/mockapp.py'

### ISSUE THREAD

**Issue by richb-hanover** [chriskiehl/Gooey#57]
Using Gooey 0.1.0 on OSX Mavericks (10.9), I did a git clone from github, then installed:
```
git clone https://github.com/chriskiehl/Gooey.git
sudo python setup.py install
```
When I try to run the mockapp.py from the mockapplications directory, I got a permission error:
```
richs-mbp-8408:mockapplications richb$ python mockapp.py
['mockapp.py']
Traceback (most recent call last):
  File "mockapp.py", line 69, in <module>
    main()
  File "/Library/Python/2.7/site-packages/Gooey-0.1.0-py2.7.egg/gooey/python_bindings/gooey_decorator.py", line 86, in inner
    with open(filepath, 'w') as f:
IOError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/Gooey-0.1.0-py2.7.egg/gooey/_tmp/mockapp.py'
```
What can I do to fix the permissions? Thanks!

NB: I used sudo on the `python setup.py install` because without sudo, I get:
```
richs-mbp-8408:Gooey richb$ python setup.py install
running install
Checking .pth file support in /Library/Python/2.7/site-packages/
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/test-easy-install-10774.pth'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /Library/Python/2.7/site-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://pythonhosted.org/setuptools/easy_install.html

Please make the appropriate changes for your system and try again.
```

**Comment by piksel** [comment]
This is because Gooey uses a temporary directory to store the python code. For some reason this points to a path under the library, which when installed as an egg is `/Library/Python/2.7/site-packages/Gooey-0.1.0-py2.7.egg/gooey/`. I don't know why the authors does this, that folder should not be modified by a application or user.

You can "fix" it by changing permissions on two folders:
> sudo chmod a+w /Library/Python/2.7/site-packages/Gooey-0.1.0-py2.7.egg/gooey/python_bindings/
> sudo chmod -R a+w /Library/Python/2.7/site-packages/Gooey-0.1.0-py2.7.egg/gooey/_tmp/

But this has some multi-user and security concerns.
I'm not sure about why the systems temp-folders are not used, that would surely be a better place to store the temporary files.

**Comment by richb-hanover** [comment]
Thanks for this info. I'm not wild about this fix: as you point out it has multi-user/security concerns. (That certainly seems to be the root of the problem.)

I haven't had time to nail this down, but I have been doing some investigation. The "Installing Python on MacOS X" page at http://docs.python-guide.org/en/latest/starting/install/osx/ tells about installing a clean environment that may avoid the permissions problems on the ...site-packages/... pages.  I will send an update if I can get definitive info.

**Comment by chriskiehl** [comment]
@piksel 

That's likely because the author is a mouth breathing Windows user! I didn't know site-packages directory on OSX had permission issues. I just dropped the temp file next to where ever Gooey's files were installed. 

As a side note... how does Gooey look on OSX? I haven't gotten around to spinning up a VM and testing anything. 

@richb-hanover 

I don't want using Gooey to involve modifying your host system. I'll fix the issue tonight! I'm guessing OSX has something similar to Window's APPDATA directory that I could safely write to. This should be fixed shortly.

**Comment by chriskiehl** [comment]
@piksel @richb-hanover 

Latest commit should fix this issue. I don't have OSX handy to test, so please let me know if things are still wacky.

**Comment by piksel** [comment]
@chriskiehl 
There's another place that has to be changed too, I'll supply a patch.
Heres how it looks:
![](http://i.imgur.com/aKdE11Z.png)
I haven't found any other problems with it yet. Everything seems to be working.

**Comment by piksel** [comment]
I made a pull request for the other change: chriskiehl/Gooey/pull/61

**Comment by chriskiehl** [comment]
@piksel 

Made a few modifications to your push. I ran across the `atexit` module, which makes cleaning up things a breeze, so I opted for `mkstemp` rather than `mkdtemp` so I only have a single file to kill at the end of execution. 

Thanks for your help!
