### ISSUE TITLE
Hooks to update the status of the progress bar

### ISSUE THREAD

**Issue by ardoramor** [chriskiehl/Gooey#60]
If the script can measure its progress, it would be nice to make calls to update the status of the progress bar instead of it being infinite.

**Comment by chriskiehl** [comment]
This one, though it would be cool, is problematic. 

Internally, Gooey no longer talks directly to the client code (your modules), but instead runs them via `popen` and gets its updates via `stdout` and `stderr`. This was done so that Gooey can be agnostic  as to the client programs implementation language (e.g. Python, Java, Go, etc..). Because it is a passive observer, there aren't any hooks which you could call to report progress. 

Now, I could get around this by parsing `stdout` for messages giving progress updates -- which, now that I'm typing it doesn't sound *too* terrible (though pretty clunky), but.. I dunno. I'd have to play around with it a bit.

**Comment by chriskiehl** [comment]
Progress bar implemented. 

Docs pending. Checkout the examples here for usage: https://github.com/chriskiehl/GooeyExamples

![image](https://cloud.githubusercontent.com/assets/1408720/11987459/c7795bf2-a9ad-11e5-98bb-7df22066f20e.png)
