### ISSUE TITLE
Optional checkbox where default=True does not return False if checkbox not ticked

### ISSUE THREAD

**Issue by GenevieveBuckley** [chriskiehl/Gooey#639]
I think I may have found a bug for optional checkboxes where the default value is specified as True.

 - [x] OS: Windows 10
 - [x] Python Version: Python 3.7
 - [x] Gooey Version: master development branch
 - [x] Thorough description of problem 
I wanted to have a True/False checkbox with a default value of True. However it seems that when you specify the default value as True, then Gooey doesn't recognize the input argument value correctly if you *uncheck* the box (i.e. set the value to False) and run the program.

     - [x] Expected Behavior 
I expect the argument value to be True whenever the checkbox is ticked, and False whenever the checkbox is not ticked.

     - [x] Actual Behavior 
        * Behaves as expected: When the default value is not specified the parsed argument is True if the checkbox is ticked, and False if the checkbox is not ticked.
        * Behaves as expected: When you specify `default=False`, the parsed argument is True if the checkbox is ticked, and False if the checkbox is not ticked.
        * Unexpected (possible bug?): When you specify `default=True`, the parsed argument value is given as True regardless of whether the checkbox was ticked or not.

 - [x] A minimal code example
If you run this code example, 
```python
from gooey import Gooey, GooeyParser

@Gooey
def main():
    parser = GooeyParser(description="Gooey example")
    parser.add_argument("-a", "--myargument", action="store_true", default=True)
    args = parser.parse_args()
    print(args)
    print(args.myargument)
    print(type(args.myargument))


if __name__=="__main__":
    main()
```

If you run this code example and uncheck the checkbox, we don't see an argument value of False like we expect. Instead we get this output:
```
Namespace(myargument=True)
True
<class 'bool'>
```

 - [ ] ~~Screenshot (if visual quirk)~~
 - [ ] ~~Anything else you may think will be helpful~~
 

Thanks! ^_^

**Comment by chriskiehl** [comment]
This trips up everyone. The key thing to remember is that Gooey is _just_ a layer for generating CLI arguments to your program. 

In CLI land, you don't pass an explicit bool for flags. The true/false is determined entirely by its presence. So, store_true means, store true _if this argument is present_. If you do not pass the `-a` argument, the value of `myargument` will, naturally, be false. But! You've also added a default value of `true`. This means that if you pass the argument you get `True` and also if you do NOT pass the argument you also get `True` (due to the default). 

In Gooey, when you click a checkbox, it includes the appropriate flag in the generated CLI string. When you deselect it, Gooey no longer sends it. 

You can verify the bool behavior by running your program without Gooey. 

Regardless of what you pass to `parse_args()` the value of `myargument` will always be True.

Hopefully that clears things up
