### ISSUE TITLE
Support for Python 4.1.0?

### ISSUE THREAD

**Issue by DankMemeGuy** [chriskiehl/Gooey#666]
Hello There, Future Issue Creator! 

>README: Are you suddenly seeing errors related to Alignment flags when starting Gooey? Upgrade your gooey installation to the latest version (`pip install -U gooey`) to resolve the errors! See [this issue](https://github.com/chriskiehl/Gooey/issues/549) for additional information. 

Found a bug? Just a friendly heads up, _debugging it requires information from you!_ Make sure the template below is filled out in its entirety. 

 - [ Windiws] OS
 - [4.1.0 ] Python Version 
 - [ 1.0.8] Gooey Version 
 - [ x] Thorough description of problem 
     - [Installation to occur ] Expected Behavior 
     - [Installation fails ] Actual Behavior 
 - [ ] A minimal code example -- preferably copy/pastable in the issue itself (less time figuring out how to run your code == more time debugging!) 
 - [https://i.imgur.com/0sapb01.png ] Screenshot (if visual quirk) 
 - [ ] Anything else you may think will be helpful 
 

Thanks! ^_^ 
 
 Looking at the error, I think it's occurring due to Python version. Is there any plans to update it? Or is it failing for something else and I just don't know? Any help would be very appreciated!

**Comment by chriskiehl** [comment]
This isn't a Gooey issue. See the issue here: https://discuss.wxpython.org/t/installing-wxpython-4-1-0-error-microsoft-visual-c-14-0-is-required-get-it-with-build-tools-for-visual-studio/34964/2 

Python 3.9 doesn't have PyPi builds yet, so WXPython tries to compile from source, which needs additional things. You can use the [snapshot builds](https://wxpython.org/Phoenix/snapshot-builds/) or downgrade Python to 3.8.x.
