### ISSUE TITLE
Compatibility with wxPython 4.1.1?

### ISSUE THREAD

**Issue by bje-** [chriskiehl/Gooey#678]
Does Gooey now work with wxPython 4.1.1? If so, can we please update the package dependencies so that we can easily install wxPython from pre-built wheels rather than source?

**Comment by chriskiehl** [comment]
Pull request loosening WX dependency to >= 4.1.0 will be happily (eventually) accepted if you want to cut a PR. 

Just as a general FYI regarding the sudden slowness of responses and activity, Gooey development has effectively been on pause for the last few months and will remain as such for another month (or so) due to the day job robbing me of any free time and/or general life (plz halp me \*blinks several times under duress\*). 

Hopefully, it'll be back to regular release and updates soon!
