### ISSUE TITLE
using Gooey with SCOOP leads to multiple windows

### ISSUE THREAD

**Issue by bje-** [chriskiehl/Gooey#686]
In case anyone in this project has ideas. I am trying to integrate https://github.com/soravux/scoop with Gooey for adding a GUI front-end for command line options (and processing) to a program that uses SCOOP for distributed computing. Since I only want one GUI window to pop up, I am running that inside the `__name__ == __main__` guard and then use the object sharing API to share the arguments with the workers. See https://github.com/soravux/scoop/issues/93 for more details.

**Comment by chriskiehl** [comment]
I've never used scoop, but this sounds kinda interesting. If it's invoking multiple processes behind the scenes, I can imagine it causing the behavior you're seeing. 

Could you drop a small code sample demoing the problem?

If I had to take a wild (and surely wrong) guess (again, literally knowing nothing about scoop), the solution to this could possibly be adjusting Gooey's `target` so that whatever process forking happens is done against a file with no gooey reference or mechanism. Just a stab in the dark, though ^_^

**Comment by bje-** [comment]
The minimal code example from issue #569 will suffice. Run it like so:

```
pip install scoop
python3 -m scoop Testcase.py
```

**Comment by bje-** [comment]
Note that the number of windows you will see depends on how many workers SCOOP decides to launch. For a quad core CPU, that will be four.

**Comment by chriskiehl** [comment]
Took a look at this. FWIW, it seems like Gooey and scoop work together fine as far as I can tell. The code sample you provide is your [other issue](https://github.com/soravux/scoop/issues/93) seems to have problems regardless of whether Gooey is involved or not. I see the `AttributeError: 'NoneType' object has no attribute 'socket'` either way. 

If I plug in the Scoop [getting started example](https://scoop.readthedocs.io/en/0.7/usage.html#mapping-api). (slightly modified to just to add Gooey, otherwise copy/pasted) e.g. 

```python
import random
from scoop import futures
from gooey import Gooey, GooeyParser

# Note the usage of target here
@Gooey(target=r'/path/to/your/python.exe -m scoop /path/to/your/script.py --ignore-gooey')
def main():
    parser = GooeyParser(description='Process some integers.')
    args = parser.parse_args()
    return [random.randint(-1000, 1000) for r in range(1000)]

if __name__ == '__main__':
    data = main()
    # Python's standard serial function
    dataSerial = list(map(abs, data))

    # SCOOP's parallel function
    dataParallel = list(futures.map(abs, data))

    assert dataSerial == dataParallel
```

The most important bit is the usage of `target`, which allows you to customize what/how Gooey invokes the subprocess. By default, Gooey just invokes the subprocess with Python directly. However, as you can see, we've customized it to invoke the target with `scoop`. 

I ran it with the instructions you provided.

```
python -m scoop myfile.py 
```

and all seems fine! 

![image](https://user-images.githubusercontent.com/1408720/129493389-c3613d16-656e-4992-a26a-5ef165d5f0f7.png)

**Comment by bje-** [comment]
Thanks a lot, Chris! I have plenty to work with here.

**Comment by bje-** [comment]
Hmm, this isn't working for me. I have:

```
scoop_opt = ' -m scoop ' if scoop_loaded_p else ' '
target_cmdline = sys.executable + scoop_opt + os.path.realpath(__file__) + ' --ignore-gooey'
```

(target_cmdline is passed to the decorator, of course). The subprocess reports:

```
prog: error: unrecognized arguments: --ignore-gooey
```

Huh?

**Comment by chriskiehl** [comment]
Give this flavor a shot: 

```python
import random
from scoop import futures
from gooey import Gooey, GooeyParser
import os
import sys


def main():
    parser = GooeyParser(description='Process some integers.')
    parser.add_argument('somepositional', help='some positional arg here')
    parser.add_argument('-a', help='some other arg')
    args = parser.parse_args()
    print(args)
    return [random.randint(-1000, 1000) for r in range(100)]

if __name__ == '__main__':
    launcher = Gooey(target=f'{sys.executable} -m scoop {os.path.realpath(__file__)}')
    decorated_main = launcher(main)
    data = decorated_main()
    # Python's standard serial function
    dataSerial = list(map(abs, data))

    # SCOOP's parallel function
    dataParallel = list(futures.map(abs, data))

    assert dataSerial == dataParallel
```

When I was playing around initially, I wasn't actually specifying any ArgParse arguments, which apparently prevented me from seeing the issue you're running into. 

So what we're doing here is moving all of Gooey's logic inside of the `__main__` guard by 'de-sugaring' the decorator and applying it by hand. We do this because Gooey currently does something pretty bad at module load time (mutates  `sys.argv`!). Ensuring that mutation is 'process safe' (used lightly) gets everything working again in a multiprocessing environment like scoop.

**Comment by bje-** [comment]
OK, so now I properly understand why I was seeing multiple Gooey windows. My `process_options()` function, previously just using `argparse`, was not inside a `__main__` guard. Fixing that means I now only get one window, but the command line arguments aren't available to all instances  at program init time like they used to (before, each instance was just parsing `sys.argv` individually).

I think the right approach is to use SCOOP's shared object API to share the arguments with each worker, but that brings me back to [this problem](https://github.com/soravux/scoop/issues/93) :-)
