### ISSUE TITLE
Framework build of python required -

### ISSUE THREAD

**Issue by Gestas** [chriskiehl/Gooey#741]
- [x] OS
 - [x] Python Version 
 - [x] Gooey Version 
 - [x] Thorough description of problem 
     - [x] Expected Behavior 
     - [x] Actual Behavior 
 - [x] A minimal code example
 - [x] Anything else you may think will be helpful 

OS: 
```
$ sw_vers
ProductName:	macOS
ProductVersion:	11.5.1
BuildVersion:	20G80
```

Python, inside a virtualenv. See repo steps:
```
$ python --version 
Python 3.8.2
``` 
Gooey Version: 
```
$ pip show Gooey
Name: Gooey
Version: 1.0.8.1
```
When trying to run any Gooey application I get this error - 
```
This program needs access to the screen. Please run with a
Framework build of python, and only when you are logged in
on the main display of your Mac.
```
Expected behavior is that the app runs without an error. 

My terminal is `iTerm2`, my shell is `/bin/zsh`. I tried `/bin/bash`, no change. 

Simple repo steps using GooeyExamples -
```
git clone https://github.com/chriskiehl/GooeyExamples.git
cd GooeyExamples
mkvirtualenv -p /usr/bin/python3 gooeyexamples
pip install -r requirements.txt
python examples/simple_demo.py

This program needs access to the screen. Please run with a
Framework build of python, and only when you are logged in
on the main display of your Mac.
$
```
I tried using `pyinstaller --windowed`, the app quits silently -
```
$ pip install pyinstaller
$ pip show pyinstaller
Name: pyinstaller
Version: 4.5.1
...
$ pyinstaller --windowed ./examples/simple_demo.py
```

I looked at #259, I didn't find a definitive solution and most of the proposed workarounds are Python 2 specific. Any suggestions appreciated.

**Comment by amin-nejad** [comment]
I believe your problem is that you're likely not using a framework build of python. I believe this happens if you're using a virtual environment. You should be using a system python. If you run `which python` it will show you what python you're using.

It should be something like `/usr/local/bin/python3.9` rather than `/Users/ali/miniconda3/envs/myEnv/bin/python`. Mac usually only comes with python 2 installed so you will need to install a version of python 3.
