### ISSUE TITLE
How to use the component of CheckBox?

### ISSUE THREAD

**Issue by Yrani6** [chriskiehl/Gooey#836]
I don't know how to use the component of checkBox.I since user it that console log always show erro return metadata['commands']
[0] if value else None IndexError: list index out of range

Please dalao give me a example to use thec CheckBox!

Please help me 3q!!!

![image](https://user-images.githubusercontent.com/64725124/187180959-f1babfab-87cb-40db-abaa-26b3de9ab42d.png)

![image](https://user-images.githubusercontent.com/64725124/187180943-0d906f92-52f4-4c9e-9070-7631d13570b5.png)

**Comment by chriskiehl** [comment]
This is a sharp edge of Gooey that should be smoothed over. The problem is that you're trying to make a _positional_ argument a checkbox, but that doesn't make sense from an argparse perspective -- something can't be optional and positional at the same time. 

So, to fix your problem, you need to swap from 

```
parser.add_argument('pidg4', ...)
```

to 

```
parser.add_argument('--pidg4', ...)   # <-- note the "--" 
```

this is how you tell argparse that you're adding an optional argument.
